# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_protocol.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'control_protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ontrol_protocol.proto\"U\n\x08Neighbor\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07node_ip\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontrol_port\x18\x03 \x01(\x05\x12\x11\n\tdata_port\x18\x04 \x01(\x05\"\xe9\x01\n\x0e\x43ontrolMessage\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.ControlMessage.Type\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0f\n\x07node_ip\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontrol_port\x18\x04 \x01(\x05\x12\x11\n\tdata_port\x18\x05 \x01(\x05\x12\x1c\n\tneighbors\x18\x06 \x03(\x0b\x32\t.Neighbor\"J\n\x04Type\x12\x0c\n\x08REGISTER\x10\x00\x12\x15\n\x11REGISTER_RESPONSE\x10\x01\x12\x14\n\x10UPDATE_NEIGHBORS\x10\x02\x12\x07\n\x03\x41\x43K\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEIGHBOR']._serialized_start=26
  _globals['_NEIGHBOR']._serialized_end=111
  _globals['_CONTROLMESSAGE']._serialized_start=114
  _globals['_CONTROLMESSAGE']._serialized_end=347
  _globals['_CONTROLMESSAGE_TYPE']._serialized_start=273
  _globals['_CONTROLMESSAGE_TYPE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
